apiVersion: apps/v1
kind: Deployment
metadata:
  name: ty-harness-demo-v1
  labels:
    app: ty-harness-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ty-harness-demo
      version: v1
  template:
    metadata:
      labels:
        app: ty-harness-demo
        version: v1
    spec:
      containers:
      - name: ty-harness-demo-v1
        image: eastyler/macdemo:v1
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "512Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ty-harness-demo-v2
  labels:
    app: ty-harness-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ty-harness-demo
      version: v2
  template:
    metadata:
      labels:
        app: ty-harness-demo
        version: v2
    spec:
      containers:
      - name: ty-harness-demo-v2
        image: eastyler/macdemo:v2
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: ty-harness-demo-service
spec:
  selector:
    app: ty-harness-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP 